# Generated by Django 4.1.3 on 2023-01-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_remove_comment_username_comment_place_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
    ]
