# Generated by Django 4.1.3 on 2023-01-30 15:25

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_remove_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="comments.comment",
            ),
        ),
    ]
