# Generated by Django 4.1.3 on 2023-01-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_tourism"),
    ]

    operations = [
        migrations.CreateModel(
            name="ethnic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("img", models.ImageField(upload_to="ethnic")),
                ("intro", models.CharField(max_length=250)),
            ],
        ),
    ]
