# Generated by Django 4.1.3 on 2023-01-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_tourism_latitude_tourism_longitude"),
    ]

    operations = [
        migrations.DeleteModel(
            name="job_detail",
        ),
    ]
