# Generated by Django 4.1.3 on 2023-01-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0009_alter_tourism_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tourism",
            options={},
        ),
    ]
