# Generated by Django 4.1.3 on 2023-01-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0010_alter_tourism_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ethnic",
            options={"verbose_name": "民族信息"},
        ),
        migrations.AlterModelOptions(
            name="pic",
            options={"verbose_name": "页面图片"},
        ),
        migrations.AlterModelOptions(
            name="tourism",
            options={"verbose_name": "旅游景点"},
        ),
    ]
