# Generated by Django 4.1.3 on 2023-01-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0012_alter_ethnic_options_alter_pic_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ethnic",
            old_name="intro",
            new_name="intro_short",
        ),
        migrations.AddField(
            model_name="ethnic",
            name="intro_long",
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
