# Generated by Django 4.1.3 on 2023-01-31 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0013_rename_intro_ethnic_intro_short_ethnic_intro_long"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ethnic",
            old_name="intro_short",
            new_name="intro",
        ),
    ]
